# Generated by Django 2.2.3 on 2019-10-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('offices', models.CharField(default='', max_length=100)),
                ('type_contact', models.CharField(choices=[(1, 'phone'), (2, 'email'), (3, 'WhatsApp'), (4, 'Telegram'), (5, 'Viber')], max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('date', models.DateField(blank=True, default='2019-01-01')),
                ('time', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('square', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('none', 'не сдаeтся'), ('free', 'свободно'), ('notfree', 'занято'), ('reserved', 'резерв')], default='free', max_length=15)),
                ('price', models.CharField(default=0, max_length=200)),
                ('type_room', models.IntegerField(default=1)),
                ('more_info', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UnionOffices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Блок офисов', max_length=200)),
                ('room_1', models.BooleanField(default=False)),
                ('room_2', models.BooleanField(default=False)),
                ('room_3', models.BooleanField(default=False)),
                ('room_4', models.BooleanField(default=False)),
                ('room_5', models.BooleanField(default=False)),
                ('room_6', models.BooleanField(default=False)),
                ('room_7', models.BooleanField(default=False)),
                ('room_8', models.BooleanField(default=False)),
                ('room_9', models.BooleanField(default=False)),
                ('room_10', models.BooleanField(default=False)),
                ('room_11', models.BooleanField(default=False)),
                ('room_12', models.BooleanField(default=False)),
                ('room_13', models.BooleanField(default=False)),
                ('room_14', models.BooleanField(default=False)),
                ('room_15', models.BooleanField(default=False)),
                ('room_16', models.BooleanField(default=False)),
                ('room_17', models.BooleanField(default=False)),
                ('room_18', models.BooleanField(default=False)),
                ('room_19', models.BooleanField(default=False)),
                ('room_20', models.BooleanField(default=False)),
                ('room_21', models.BooleanField(default=False)),
                ('room_22', models.BooleanField(default=False)),
                ('room_23', models.BooleanField(default=False)),
                ('room_24', models.BooleanField(default=False)),
                ('room_25', models.BooleanField(default=False)),
                ('room_26', models.BooleanField(default=False)),
                ('room_27', models.BooleanField(default=False)),
                ('room_28', models.BooleanField(default=False)),
                ('room_29', models.BooleanField(default=False)),
                ('room_30', models.BooleanField(default=False)),
                ('room_31', models.BooleanField(default=False)),
                ('room_32', models.BooleanField(default=False)),
                ('room_33', models.BooleanField(default=False)),
                ('room_34', models.BooleanField(default=False)),
                ('room_35', models.BooleanField(default=False)),
                ('room_36', models.BooleanField(default=False)),
                ('room_37', models.BooleanField(default=False)),
                ('room_38', models.BooleanField(default=False)),
                ('room_39', models.BooleanField(default=False)),
                ('room_40', models.BooleanField(default=False)),
                ('room_41', models.BooleanField(default=False)),
                ('room_42', models.BooleanField(default=False)),
                ('room_43', models.BooleanField(default=False)),
                ('room_44', models.BooleanField(default=False)),
                ('room_45', models.BooleanField(default=False)),
                ('room_46', models.BooleanField(default=False)),
                ('room_47', models.BooleanField(default=False)),
            ],
        ),
    ]
